config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "posts/my", to: 'posts#my_posts', as: "my_posts"

  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  has_rich_text :content

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(params.require(:comment).permit(:content))
    @comment.user = current_user
    if @comment.save
      redirect_to @post, note: "Comment added."
    else
      redirect_to @post, alert: "Could not add comment."
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('created_at DESC').where(status: 'published')
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def my_posts
    @posts = current_user.posts
    @header = "My Posts"
    render "posts/index"
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    if current_user.id == @post.user_id
      render :edit
    else
      redirect_to post_url(@post), alert: "You cannot edit another user's post"
    end
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    if current_user.id == @post.user_id
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to post_url(@post), alert: "You are not authorized to delete this post"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>>">
  <% if comment.user&.email %>
    <strong><%= comment.user.email %></strong>:
  <% end %>
  <%= comment.content %>
  - <%= time_tag comment.created_at, "data-local": "time-ago"  %>
</div>

<!-- TODO: Implement delete post-->

app/views/comments/_new.html.erb
<% if user_signed_in? %>
  <%= form_with model: [post, Comment.new] do |form| %>
    <%= form.label :content, "Your Comment:" %>
    <%= form.text_area :content, size: "20x5", class: "form-control"%>
    <%= form.submit "Add Comment", class: "btn btn-primary mt-4" %>
  <% end %>
<% else %>
  <%= link_to "Sign in to comment", new_user_session_path, class: "btn btn-primary mb-4" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/alert" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_comments.html.erb
<hr>
<h3>Comments</h3>
<div id="comments">
  <%= render partial: "comments/comment", collection: post.comments %>
</div>

<%= render "comments/new", post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, [%w[Draft draft], %w[Published published]],
                    {}, {class: "form-select"} %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Cancel', @post, class: "btn btn-secondary mt-2" %>

app/views/posts/index.html.erb
<div class="posts-container">
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary new-post" %>
  <h1><%= @header ? @header : "Posts" %></h1>
  <hr>

  <% if @posts.length == 0 %>
    <div class="alert alert-danger" role="alert">
      No posts to show
    </div>
    <%= link_to "Create New Post", new_post_path, class: "btn btn-primary mt-4" %>
  <% end %>

  <% @posts.each do |post| %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text post-content"><%= post.content %></p>
      <p class="card-text"><%= pluralize post.comments.count, "comment" %></p>
      <%= link_to 'Read more..', post, class: "btn btn-primary" %>
      <% if post.user&.email == current_user&.email %>
          <%= link_to 'Edit', edit_post_path(post), class: "btn" %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: "btn btn-secondary mt-2" %>

app/views/posts/show.html.erb
<div class="show-post">

  <% if @post.user&.email == current_user&.email %>
    <%= link_to 'Delete', @post,
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: "btn btn-danger float-end" %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary float-end me-2"%>
  <% end %>
  <h1>
    <%= @post.title %>
  </h1>
  <p>
    <small>
      <%= time_tag @post.created_at, "data-local": "time-ago" %>
    </small>
  </p>
  <hr>
  <p>
    <%= @post.content %>
  </p>
  <%= render 'posts/comments', post: @post %>
</div>

app/views/shared/_alert.html.erb
<div class="alert-container mt-4">
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>
  <% if notice %>
    <div class="alert alert-primary" role="alert">
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Nonstop io - Blogs", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
<!--          <a class="nav-link active" aria-current="page" href="">Home</a>-->
        </li>
        <li class="nav-item">
          <%= link_to "My Posts", my_posts_path, class: "nav-link" %>
        </li>
      </ul>

      <% if user_signed_in? %>
        <span class="welcome-user">Welcome <%= current_user.email %>, </span>,
      <% end %>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Settings
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <% if user_signed_in? %>
            <li>
              <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign in", new_user_session_path, class: "dropdown-item"  %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item"  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>